### ISSUE TITLE
LiveCloudKd for live debugging not working

### ISSUE THREAD

**Issue by yoro12341234** [gerhart01/LiveCloudKd#1]
Hello, I am trying to use LiveCloudKd as explained in the LiveDebugging tutorial, but unfortunately it doesn't work.
My goal is to debug the securekernel with windbg, I understand this tool can achieve it.

I believe there are multiple problems:
1. It seems the source code in the repository does not match the binary in the published releases (we can see that the usage differ)
2. When using the released binaries, I am able to capture a live dump and debug it with kd.exe but any of the flags /w (use windbg) or /l (live debugging) or /e (use exdi) do not seem to affect the flow and it's always run the same thing (loading the live dump of the VM)

I would much appreciate your assistance, Thanks

**Comment by gerhart01** [comment]
Hi. Yes, latest public version of LiveCloudKd doesn't support live debugging. Probably, i will return this option someday.
You can try old LiveCloudKd version, that support live debugging - https://github.com/gerhart01/LiveCloudKd/releases/tag/v2.0.0.20200308-beta

**Comment by yoro12341234** [comment]
Ok Thanks! 
I hope you will return this option in the latest release :)

**Comment by gerhart01** [comment]
Updated release - https://github.com/gerhart01/LiveCloudKd/releases/download/v1.0.22021109/LiveCloudKd.EXDi.debugger.v1.0.22021109.zip
And updated instruction - https://github.com/gerhart01/LiveCloudKd/blob/master/ExdiKdSample/LiveDebugging.md
