### ISSUE TITLE
Some additonal info about my previous issue aka /issues/9

### ISSUE THREAD

**Issue by ullMarksin** [gerhart01/LiveCloudKd#10]
About MemProcFS plugin
Your new README.md says 
Hyper-V Virtual Machine plugin for MemProcFS.  Download ->
https://github.com/gerhart01/LiveCloudKd/releases/download/v2.5.5.20220914/leechcore_hyperv_plugin_14.09.2022.zip

Technically plugin should work alone, but your leechcore_hyperv_plugin_14.09.2022.zip doesn't include hvmm.sys

leechcore_hyperv_plugin_14.09.2022.zip  Content:
LiveCloudKd.exe
hvlib.dll
leechcore_device_hvmm.dll

So MemProcFS throws error about hvmm.sys missing:
MemProcFS.exe -device hvmm://id=0
DEVICE_HVMM: ERROR: unable to locate driver file 'C:\test\memproc5\hvmm.sys'.
DEVICE_HVMM: FAILED: Failed to initialize the driver.
MemProcFS: Failed to connect to memory acquisition device.

To fix problem you need to download not plugin aka
https://github.com/gerhart01/LiveCloudKd/releases/download/v2.5.5.20220911/LiveCloudKd.v2.5.5.20220911-release.zip
and extract hvmm.sys to MemProcFS folder

and this where my /issues/9 comes from

**Comment by gerhart01** [comment]
Thanks for detailed description! 
I fixed it and upload correct distributive.
Btw, you can simply wrote "current leechcore Hyper-V plugin doesn't contain driver hvmm.sys" )
