### ISSUE TITLE
Please help me, cant debug step by step and breakpoints are not work

### ISSUE THREAD

**Issue by anhkgg** [gerhart01/LiveCloudKd#11]
Hi, gerhart01, thanks for your tools.

LiveCloundKd is not working well for me, please help me, thank you.

version: https://github.com/gerhart01/LiveCloudKd/releases/download/v1.0.22021109/LiveCloudKd.EXDi.debugger.v1.0.22021109.zip
I try with the document: https://github.com/gerhart01/LiveCloudKd/blob/master/ExdiKdSample/LiveDebugging.md
1. WinDBG x64 10.0.22621 can debug sk step by step and bp is ok when I install it firstly, but no symbol, and it cant work in second time.
2. Other version windbg can get the right symols, but cant debug sk step by step .

How can I do, thank you!

**Comment by gerhart01** [comment]
Hello.
What does show command:
.reload /f securekernel.exe=<module_base_address>?

**Comment by anhkgg** [comment]
0: kd> .reload /f securekernel=0xfffff80773a67000

ModLoad: fffff807`73a67000 fffff807`73bb7000   securekernel

Thank you.
1. But the most important thing is not symbol, I can't debug sk by single step command,
2. The breakpoint is work but windbg can't stop when breakpoint was triggered, I break windbg and the rip is on breakpoint
3. Also windbg is so easy to lost, and then can't debug.

**Comment by gerhart01** [comment]
Perfect, it means securekernel.exe is loaded - you can see end address of loading.
1. Be sure, that host OS is Windows Server 2019 from 08.2020 (image name is presented in LiveDebugging.md document)
2. Try WinDBG Preview 1.2104.13002.0 (https://disk.yandex.com/d/9VLm5ou6W5UBrA) - i checked it now, its working
![Screen](https://user-images.githubusercontent.com/25981258/210237731-b0db05a4-2f6e-4fda-ace2-beea68258af9.png)

**Comment by anhkgg** [comment]
Thank you so much, I will try again.

**Comment by gerhart01** [comment]
Good.
I close issue. If you will have another problem, you can reopen this case or open new.
