### ISSUE TITLE
Unable to find base kernel modules and start debugging

### ISSUE THREAD

**Issue by JustaT3ch** [gerhart01/LiveCloudKd#14]
Hello,

I am trying to debug the secure kernel, but it seem to fail when it attempts to find the kernel modules in memory
If I run livecloudkd several times it sometimes locates the normal kernel and not the secure kernel but when I run it again
both kernels are not found:
hvlib:kernel base is not found
hvlib:kernel base is not found

Another error I get which might be related : open registry key vmld was failed.

I am running Windows server 2019 in a nested virtualization in VM workstation as the host and as the guest Windows 11.

Any idea what could be the issue in this case? If its only related to the vmld failure, then do you have any idea how to resolve that issue?

P.S. everything was ran as admin with the same privilege level

Thank you,

**Comment by JustaT3ch** [comment]
Another note : the release version I used 1.0.22021109

**Comment by gerhart01** [comment]
Hello.
Yes, you are using correct configuration and LiveCloudKd version (also, don't forget that you have to use Windows Server 2019 build with August 2020 updates).
Please, say, what Windows 11 build you try to investigate

**Comment by JustaT3ch** [comment]
Hello, 

I am using Windows 11 version 22H2 (22621.1702)

**Comment by gerhart01** [comment]
Ok.
I will try to reproduce your issue.

**Comment by JustaT3ch** [comment]
Update: I was able to make it work by changing the version of the windows server.
I was not able to make it work in any other situation i.e. with the host being windows 11 or 10

is there a version which will work with those windows version ?

**Comment by JustaT3ch** [comment]
Have you encountered a case where by setting breakpoint cased BSOD in the Win 11 machine?

**Comment by gerhart01** [comment]
I checked debugger on guest Windows 11 with August 2023 patches - it working.
WinDBG with modern GUI for static analyzing can be used, but for debugging i still recommend WinDBG from Windows SDK\WDK.
Debugger works with Windows Server 2019 as host version. I didn't check it with host Windows 10 or 11 - it can cause BSOD on it.
![image](https://github.com/gerhart01/LiveCloudKd/assets/25981258/8f2f4e7d-35ec-49d9-b431-7cae7bd34cbc)

**Comment by JustaT3ch** [comment]
My host is Server 2019 as mentioned in you notes(august patch: en_windows_server_2019_updated_aug_2020_x64_dvd_f4bab427.iso) and I am using the standard windbg from SDK
BSOD in breakpoint.
Any ideas why that might happen?

**Comment by gerhart01** [comment]
You can run Hyper-V host and guest inside VMware Workstation or, probably, in Hyper-V on Windows 11 (didn't test this configuration). I mean Windows11 -> Windows Server 2019 (august 2020 patches)->Windows 11 as nested guest. I don't have much time for testing it on different Windows.

About BSOD:
1. First check pagefile inside guest OS - disable it, if it presented
2. Create enough amount of memory for Host OS
3. Set 1 CPU for guest OS

**Comment by gerhart01** [comment]
Also it not be bad if you check WinDBG with modern UI. It looks like latest version (1.2308) is working.
There was a good advice from previous ticket to launch it from cmd-line:

`DbgX.Shell.exe -v -kx exdi:CLSID={67030926-1754-4FDA-9788-7F731CBDAE42},Kd=Guess`

![image](https://github.com/gerhart01/LiveCloudKd/assets/25981258/bbbf32db-91e5-45bb-a97a-33146bea31a6)

**Comment by JustaT3ch** [comment]
In the case of modern windbg, which folder should I copy the livecloudkd file?

**Comment by JustaT3ch** [comment]
The crash is still happening after memory increase and disable of the page file and setting 1 CPU.
I also tried using windbg gui. 
![image](https://github.com/gerhart01/LiveCloudKd/assets/91199890/eaef3c22-174b-41df-95d1-98699d15b9be)
I will send send you a crash dump

**Comment by gerhart01** [comment]
For modern WinDBG you have to simple register EXDi plugin using regsvr32 and launch it from command line. Folder for LiveCloudKd can be any, i think.
BSOD from guest OS means, that VM don't start correctly. Please, show Windows kernel version from host OS.

**Comment by gerhart01** [comment]
Log inside WinDBG must be looked as next:
`************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       SRV*C:\Symbols*https://msdl.microsoft.com/download/symbols
Symbol search path is: SRV*C:\Symbols*https://msdl.microsoft.com/download/symbols
Executable search path is: 
Loading symbols for fffff806`30000000     ntkrnlmp.exe ->   ntkrnlmp.exe
ModLoad: fffff806`30000000 fffff806`31047000   ntkrnlmp.exe
Windows 10 Kernel Version 22000 MP (2 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Edition build lab: 22000.1.amd64fre.co_release.210604-1628
Kernel base = 0xfffff806`30000000 PsLoadedModuleList = 0xfffff806`30c29740
Debug session time: Sat Oct  7 06:45:16.702 2023 (UTC - 7:00)
System Uptime: 0 days 0:52:43.624
nt!PpmIdleGuestExecute+0x1d:
fffff806`3039d30d 48c1e220        shl     rdx,20h`

**Comment by gerhart01** [comment]
Also verify, that you don't have another EXDi plugin on host OS, registered early.

**Comment by JustaT3ch** [comment]
kernel version of the host OS:
![image](https://github.com/gerhart01/LiveCloudKd/assets/91199890/b36eabd8-35f6-4d87-a0f4-8062804a5d97)

windbg log :
************* Preparing the environment for Debugger Extensions Gallery repositories **************
   ExtensionRepository : Implicit
   UseExperimentalFeatureForNugetShare : false
   AllowNugetExeUpdate : false
   AllowNugetMSCredentialProviderInstall : false
   AllowParallelInitializationOfLocalRepositories : true

   -- Configuring repositories
      ----> Repository : LocalInstalled, Enabled: true
      ----> Repository : UserExtensions, Enabled: true

>>>>>>>>>>>>> Preparing the environment for Debugger Extensions Gallery repositories completed, duration 0.000 seconds

************* Waiting for Debugger Extensions Gallery to Initialize **************

>>>>>>>>>>>>> Waiting for Debugger Extensions Gallery to Initialize completed, duration 0.016 seconds
   ----> Repository : UserExtensions, Enabled: true, Packages count: 0
   ----> Repository : LocalInstalled, Enabled: true, Packages count: 36

Microsoft (R) Windows Debugger Version 10.0.25877.1004 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

EXDI: DbgCoInitialize returned 0x00000001
EXDI: CoCreateInstance() returned 0x00000000
EXDI: QueryInterface(IExdiServer3) returned 0x00000000
Interface is not implemented by COM server. ExecuteServerCommand() failed getting the IeXdiControlComponentFunctions pointer: 0x80004002
EXDI: Server::GetTargetInfo() returned 0x00000000
EXDI: Server::SetKeepaliveInterface() returned 0x00000000
EXDI: Server::GetNbCodeBpAvail() returned 0x00000000
EXDI: ExdiNotifyRunChange::Initialize() returned 0x00000000
EXDI: LiveKernelTargetInfo::Initialize() returned 0x00000000
EXDI: Target initialization succeeded
Kernel Debugger connection established
Searching for module base address...
Obtaining the System Application base address...
CPU: 0, Vector Address: 0xfffff8014fa3fdc0, Memory space = Supervisor-Kernel
Found a potential PE image at 0xfffff8014f7ef000. Scanning image headers...
Analyzing debug directory of module at 0xfffff8014f7ef000...
Reading debug directory header at offset 0...
Debug directory RVA=0x3eb77774, size=1053496848...
Unsupported debug information format: 1054087823
Reading debug directory header at offset 28...
Debug directory RVA=0x3e1c4eb1, size=1047384783...
Unsupported debug information format: 1049006307
Reading debug directory header at offset 56...
Debug directory RVA=0x3d8115e0, size=0...
Unsupported debug information format: 0
Found a potential PE image at 0xfffff8014f7e1000. Scanning image headers...
Analyzing debug directory of module at 0xfffff8014f7e1000...
Reading debug directory header at offset 0...
Debug directory RVA=0xa7a78686, size=1717986918...
Unsupported debug information format: 1717965845
Reading debug directory header at offset 28...
Debug directory RVA=0x86868686, size=1712591892...
Unsupported debug information format: 353703235
Reading debug directory header at offset 56...
Debug directory RVA=0x66666666, size=336925973...
Unsupported debug information format: 1126310434
Found a potential PE image at 0xfffff8014f7d4000. Scanning image headers...
Analyzing debug directory of module at 0xfffff8014f7d4000...
Reading debug directory header at offset 0...
Debug directory RVA=0x8bffffe8, size=-1946651137...
Unsupported debug information format: 842
Reading debug directory header at offset 28...
Debug directory RVA=0xea35e837, size=-126484720...
Unsupported debug information format: 1946436484
Reading debug directory header at offset 56...
Debug directory RVA=0xe8000003, size=-2047833089...
Unsupported debug information format: -951832
Found a potential PE image at 0xfffff8014f7c8000. Scanning image headers...
Analyzing debug directory of module at 0xfffff8014f7c8000...
Reading debug directory header at offset 0...
Debug directory RVA=0xf90c143, size=1207959679...
Unsupported debug information format: -256
Reading debug directory header at offset 28...
Debug directory RVA=0xb4, size=1149830376...
Unsupported debug information format: -2097152000
Reading debug directory header at offset 56...
Debug directory RVA=0x908d, size=-947172348...
Unsupported debug information format: 1301105696
Reading debug directory header at offset 84...
Debug directory RVA=0x45c6ffff, size=1569390592...
Unsupported debug information format: 47048964
Found a potential PE image at 0xfffff8014f773000. Scanning image headers...
Analyzing debug directory of module at 0xfffff8014f773000...
Reading debug directory header at offset 0...
Debug directory RVA=0x2300, size=50...
The image at 0xfffff8014f773000 has a PDB path of mcupdate_GenuineIntel.pdb
The module at 0xfffff8014f773000 refers to mcupdate_GenuineIntel
Found Module Name mcupdate_GenuineIntel
Found a potential PE image at 0xfffff8014f773000. Scanning image headers...
Analyzing debug directory of module at 0xfffff8014f773000...
Reading debug directory header at offset 0...
Debug directory RVA=0x2300, size=50...
The image at 0xfffff8014f773000 has a PDB path of mcupdate_GenuineIntel.pdb
The module at 0xfffff8014f773000 refers to mcupdate_GenuineIntel
Found Module Name mcupdate_GenuineIntel
Searching for mcupdate_GenuineIntel!KdVersionBlock...
Overriding symbol path for mcupdate_GenuineIntel!KdVersionBlock location to SRV*C:\Symbols*https://msdl.microsoft.com/download/symbols
The following symbol path will be used to find mcupdate_GenuineIntel kernel symbols: SRV*C:\Symbols*https://msdl.microsoft.com/download/symbols
SymFromName() could not find the location of mcupdate_GenuineIntel!KdVersionBlock. Check your symbol path.
Could not find the location of KdVersionBlock. Please enable the verbose mode for more details.
CPU 0: PC = 0xfffff8014fa429c0, SP = 0x205257b190
Found a potential PE image at 0xfffff8014f7ef000. Scanning image headers...
Analyzing export table of module at 0xfffff8014f7ef000...
Fetched export directory header. Name offset is -858993460
The image at 0xfffff8014f7ef000 is 
Looking for imports from current module...
Found DLL import descriptor for , function address vector at 0xfffff801d48ec83b
Found DLL import descriptor for , function address vector at 0xfffff80198a7d1ba
Found DLL import descriptor for MZ, function address vector at 0xfffff80190fef000
Found DLL import descriptor for , function address vector at 0xfffff8014f7fc482
Found DLL import descriptor for , function address vector at 0xfffff8016fd5a70f
Found DLL import descriptor for , function address vector at 0xfffff8014f878585
Found DLL import descriptor for , function address vector at 0xfffff8015016740f
Found DLL import descriptor for , function address vector at 0xfffff801a60a38c5
Found DLL import descriptor for , function address vector at 0xfffff8015f4f2b48
Found DLL import descriptor for , function address vector at 0xfffff801537ed181
Found DLL import descriptor for , function address vector at 0xfffff80197e41c75
Found DLL import descriptor for , function address vector at 0xfffff8018ac00872
Found DLL import descriptor for , function address vector at 0xfffff8014fa50f89
Found DLL import descriptor for (%, function address vector at 0xfffff801d38eb085
Found DLL import descriptor for , function address vector at 0xfffff801be0c3c20
Found DLL import descriptor for MZ, function address vector at 0xfffff801cf7ef000
Found DLL import descriptor for , function address vector at 0xfffff80171c57820
Found DLL import descriptor for , function address vector at 0xfffff801d38e10a8
Found DLL import descriptor for , function address vector at 0xfffff80197974e21
Found DLL import descriptor for , function address vector at 0xfffff801d38df1c3
Found DLL import descriptor for , function address vector at 0xfffff80230f5f0a3
Found DLL import descriptor for , function address vector at 0xfffff802100a38d2
Found DLL import descriptor for , function address vector at 0xfffff801dac7efff
Found DLL import descriptor for , function address vector at 0xfffff8019900ff3f
Found DLL import descriptor for , function address vector at 0xfffff801987f9358
Found DLL import descriptor for , function address vector at 0xfffff80153c17bd0
Found DLL import descriptor for , function address vector at 0xfffff8018e9e7000
Found DLL import descriptor for , function address vector at 0xfffff8024bfd2f1f
Found DLL import descriptor for , function address vector at 0xfffff8015145e641
Found DLL import descriptor for , function address vector at 0xfffff8014f7ef64e
Found DLL import descriptor for , function address vector at 0xfffff8019ef1fae1
Found DLL import descriptor for , function address vector at 0xfffff802490a3800
Found DLL import descriptor for , function address vector at 0xfffff801978fefc1
Found DLL import descriptor for , function address vector at 0xfffff8022b043828
Found DLL import descriptor for , function address vector at 0xfffff801987ef008
Found DLL import descriptor for , function address vector at 0xfffff80150c17d48
Found DLL import descriptor for , function address vector at 0xfffff80199492348
Found DLL import descriptor for RichÎì¡, function address vector at 0xfffff802098e38f0
Found DLL import descriptor for , function address vector at 0xfffff802068e1246
Found DLL import descriptor for Tèauhèauxèauèauèau¬ãau, function address vector at 0xfffff8014f7faa48
Found a reference to .
Found a reference to .
Found a reference to MZ.
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to (%.
Found a reference to .
Found a reference to MZ.
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to .
Found a reference to RichÎì¡.
Found a reference to .
Found a reference to Tèauhèauxèauèauèau¬ãau.
Could not find NT kernel location based on program counter register.
Could not find the location of KdVersionBlock. Please enable the verbose mode for more details.
Debug API version does not match system version
64-bit machine not using 64-bit API
Debugger data list address is NULL
Connected to eXDI Device 0 x64 target at (Sat Oct  7 17:48:21.254 2023 (UTC + 3:00)), ptr64 TRUE

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       SRV*C:\Symbols*https://msdl.microsoft.com/download/symbols
Symbol search path is: SRV*C:\Symbols*https://msdl.microsoft.com/download/symbols
Executable search path is: 
Module List address is NULL - debugger not initialized properly.
WARNING: .reload failed, module list may be incomplete
KdDebuggerDataBlock not available!
KdDebuggerData.KernBase < SystemRangeStart
eXDI Device Kernel Version 0 UP Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Primary image base = 0x00000000`00000000 Loaded module list = 0x00000000`00000000
System Uptime: not available
fffff801`4f8af1b2 0fb65139        movzx   edx,byte ptr [rcx+39h]

**Comment by gerhart01** [comment]
try to run LiveCloudKd without EXDi plugin and attach to guest OS

**Comment by gerhart01** [comment]
WinDBG log from Windows 11 September 2023 updates:
```
Microsoft (R) Windows Debugger Version 10.0.25921.1001 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

EXDI: DbgCoInitialize returned 0x00000001
EXDI: CoCreateInstance() returned 0x00000000
EXDI: QueryInterface(IExdiServer3) returned 0x00000000
Interface is not implemented by COM server. ExecuteServerCommand() failed getting the IeXdiControlComponentFunctions pointer: 0x80004002
EXDI: Server::GetTargetInfo() returned 0x00000000
EXDI: Server::SetKeepaliveInterface() returned 0x00000000
EXDI: Server::GetNbCodeBpAvail() returned 0x00000000
EXDI: ExdiNotifyRunChange::Initialize() returned 0x00000000
EXDI: LiveKernelTargetInfo::Initialize() returned 0x00000000
EXDI: Target initialization succeeded
Kernel Debugger connection established
Searching for module base address...
Obtaining the System Application base address...
CPU: 0, Vector Address: 0xfffff8031302b040, Memory space = Supervisor-Kernel
Found a potential PE image at 0xfffff80312dff000. Scanning image headers...
Analyzing debug directory of module at 0xfffff80312dff000...
Reading debug directory header at offset 0...
Debug directory RVA=0x4800a045, size=1218467213...
Unsupported debug information format: 1207959553
Reading debug directory header at offset 28...
Debug directory RVA=0x88250c8b, size=-833951720...
Unsupported debug information format: 1317750784
Reading debug directory header at offset 56...
Debug directory RVA=0xf01f883, size=1183514661...
Unsupported debug information format: -848459761
Reading debug directory header at offset 84...
Debug directory RVA=0x4e02e8a8, size=-59927...
Unsupported debug information format: 8827452
Found a potential PE image at 0xfffff80312df6000. Scanning image headers...
Analyzing debug directory of module at 0xfffff80312df6000...
Reading debug directory header at offset 0...
Debug directory RVA=0x0, size=0...
Unsupported debug information format: 0
Reading debug directory header at offset 28...
Debug directory RVA=0x0, size=0...
Unsupported debug information format: 0
Reading debug directory header at offset 56...
Debug directory RVA=0x0, size=0...
Unsupported debug information format: 0
Reading debug directory header at offset 84...
Debug directory RVA=0x0, size=0...
Unsupported debug information format: 0
Found a potential PE image at 0xfffff80312de5000. Scanning image headers...
Analyzing debug directory of module at 0xfffff80312de5000...
Reading debug directory header at offset 0...
Debug directory RVA=0x44000d46, size=1222019912...
Unsupported debug information format: -947172352
Reading debug directory header at offset 28...
Debug directory RVA=0x820f09e2, size=-1962925039...
Unsupported debug information format: -142274561
Reading debug directory header at offset 56...
Debug directory RVA=0xfc08400, size=-880064257...
Unsupported debug information format: -236147
Found a potential PE image at 0xfffff80312dd6000. Scanning image headers...
Analyzing debug directory of module at 0xfffff80312dd6000...
Reading debug directory header at offset 0...
Debug directory RVA=0x1483e, size=713884...
Unsupported debug information format: 83627
Reading debug directory header at offset 28...
Debug directory RVA=0xad918, size=84400...
Unsupported debug information format: 710936
Reading debug directory header at offset 56...
Debug directory RVA=0x14e10, size=85514...
Unsupported debug information format: 85152
Reading debug directory header at offset 84...
Debug directory RVA=0x15288, size=711572...
Unsupported debug information format: 86276
Found a potential PE image at 0xfffff80312dba000. Scanning image headers...
Analyzing debug directory of module at 0xfffff80312dba000...
Reading debug directory header at offset 0...
Debug directory RVA=0xd5810003, size=1653604355...
Unsupported debug information format: -692191229
Reading debug directory header at offset 28...
Debug directory RVA=0x627f0002, size=1652490243...
Unsupported debug information format: -692191229
Reading debug directory header at offset 56...
Debug directory RVA=0xd6be0003, size=-692191230...
Unsupported debug information format: 1652490242
Reading debug directory header at offset 84...
Debug directory RVA=0xd6be0003, size=-692191229...
Unsupported debug information format: -692191229
Found a potential PE image at 0xfffff80312d9b000. Scanning image headers...
Analyzing debug directory of module at 0xfffff80312d9b000...
Reading debug directory header at offset 0...
Debug directory RVA=0x7263206f, size=1818845510...
Unsupported debug information format: 3044213
Reading debug directory header at offset 28...
Debug directory RVA=0x616c6320, size=543515502...
Unsupported debug information format: 1635021678
Reading debug directory header at offset 56...
Debug directory RVA=0x65006d, size=7471205...
Unsupported debug information format: 7733362
Reading debug directory header at offset 84...
Debug directory RVA=0x6d614e72, size=1395073140...
Unsupported debug information format: 1970282607
Found a potential PE image at 0xfffff80312d95000. Scanning image headers...
Analyzing debug directory of module at 0xfffff80312d95000...
Reading debug directory header at offset 0...
Debug directory RVA=0x0, size=0...
Unsupported debug information format: 0
Reading debug directory header at offset 28...
Debug directory RVA=0x7028, size=12...
Unsupported debug information format: 1
Reading debug directory header at offset 56...
Debug directory RVA=0x24e8, size=9328...
Unsupported debug information format: 9276
Reading debug directory header at offset 84...
Debug directory RVA=0x2894, size=10320...
Unsupported debug information format: 9852
Found a potential PE image at 0xfffff80312d89000. Scanning image headers...
Analyzing debug directory of module at 0xfffff80312d89000...
Reading debug directory header at offset 0...
Debug directory RVA=0x80013ec, size=-355465216...
Unsupported debug information format: 334045192
Reading debug directory header at offset 28...
Debug directory RVA=0x13f86008, size=134222836...
Unsupported debug information format: 1611137043
Reading debug directory header at offset 56...
Debug directory RVA=0xf0080013, size=335417352...
Unsupported debug information format: 1309888
Reading debug directory header at offset 84...
Debug directory RVA=0x140a90, size=1342701588...
Unsupported debug information format: 127928320
Found a potential PE image at 0xfffff80312d7e000. Scanning image headers...
Analyzing debug directory of module at 0xfffff80312d7e000...
Reading debug directory header at offset 0...
Debug directory RVA=0x6030602, size=1880109588...
Unsupported debug information format: 406548
Reading debug directory header at offset 28...
Debug directory RVA=0xc0, size=28688...
Unsupported debug information format: 1704215
Reading debug directory header at offset 56...
Debug directory RVA=0xc011e013, size=1324060...
Unsupported debug information format: 1401884
Reading debug directory header at offset 84...
Debug directory RVA=0x40602, size=115064...
Unsupported debug information format: 114893
Found a potential PE image at 0xfffff80312d6a000. Scanning image headers...
Analyzing debug directory of module at 0xfffff80312d6a000...
Reading debug directory header at offset 0...
Debug directory RVA=0x43005c, size=7602291...
Unsupported debug information format: 7929939
Reading debug directory header at offset 28...
Debug directory RVA=0x53006c, size=7602286...
Unsupported debug information format: 7274563
Reading debug directory header at offset 56...
Debug directory RVA=0x4d0054, size=7077999...
Unsupported debug information format: 7471220
Reading debug directory header at offset 84...
Debug directory RVA=0x690061, size=6488174...
Unsupported debug information format: 6357110
Found a potential PE image at 0xfffff80312d63000. Scanning image headers...
Analyzing debug directory of module at 0xfffff80312d63000...
Reading debug directory header at offset 0...
Debug directory RVA=0x0, size=0...
Unsupported debug information format: 0
Reading debug directory header at offset 28...
Debug directory RVA=0x0, size=0...
Unsupported debug information format: 0
Reading debug directory header at offset 56...
Debug directory RVA=0x0, size=0...
Unsupported debug information format: 0
Reading debug directory header at offset 84...
Debug directory RVA=0x0, size=0...
Unsupported debug information format: 0
Found a potential PE image at 0xfffff80312c00000. Scanning image headers...
Analyzing debug directory of module at 0xfffff80312c00000...
Reading debug directory header at offset 0...
Debug directory RVA=0x47bb0, size=37...
The image at 0xfffff80312c00000 has a PDB path of ntkrnlmp.pdb
The module at 0xfffff80312c00000 refers to ntkrnlmp
Found Module Name ntkrnlmp
Found a potential PE image at 0xfffff80312c00000. Scanning image headers...
Analyzing debug directory of module at 0xfffff80312c00000...
Reading debug directory header at offset 0...
Debug directory RVA=0x47bb0, size=37...
The image at 0xfffff80312c00000 has a PDB path of ntkrnlmp.pdb
The module at 0xfffff80312c00000 refers to ntkrnlmp
Found Module Name ntkrnlmp
Searching for nt!KdVersionBlock...
Overriding symbol path for nt!KdVersionBlock location to SRV*C:\Symbols*https://msdl.microsoft.com/download/symbols
The following symbol path will be used to find nt kernel symbols: SRV*C:\Symbols*https://msdl.microsoft.com/download/symbols
Overriding symbol path for nt!BdInfiniteLoop location to SRV*C:\Symbols*https://msdl.microsoft.com/download/symbols
The following symbol path will be used to find nt kernel symbols: SRV*C:\Symbols*https://msdl.microsoft.com/download/symbols
SymFromName() could not find the location of nt!BdInfiniteLoop. Check your symbol path.
Found KdVersionBlock at 0xfffff803138097d8
Found target VersionBlock at 0xfffff803138097d8
Connected to Windows 10 22000 x64 target at (Sat Oct  7 08:59:56.850 2023 (UTC - 7:00)), ptr64 TRUE

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       SRV*C:\Symbols*https://msdl.microsoft.com/download/symbols
Symbol search path is: SRV*C:\Symbols*https://msdl.microsoft.com/download/symbols
Executable search path is: 
Loading symbols for fffff803`12c00000     ntkrnlmp.exe ->   ntkrnlmp.exe
ModLoad: fffff803`12c00000 fffff803`13c47000   ntkrnlmp.exe
Windows 10 Kernel Version 22000 MP (2 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Edition build lab: 22000.1.amd64fre.co_release.210604-1628
Kernel base = 0xfffff803`12c00000 PsLoadedModuleList = 0xfffff803`13829840
Debug session time: Sat Oct  7 08:59:54.830 2023 (UTC - 7:00)
System Uptime: 0 days 0:03:12.253
nt!PpmIdleGuestExecute+0x1d:
fffff803`12f9d26d 48c1e220        shl     rdx,20h
0: kd> .reload /f securekernel.exe=0xfffff8031b58e000
Loading symbols for fffff803`1b58e000 securekernel.exe ->   securekernel.exe
ModLoad: fffff803`1b58e000 fffff803`1b6ac000   securekernel.exe
0: kd> bp securekernel!IumInvokeSecureService
0: kd> g
Breakpoint 0 hit
securekernel!IumInvokeSecureService:
```

**Comment by gerhart01** [comment]
And switch to latest modern WinDBG (1.2308.2002.0), please, for testing.

**Comment by JustaT3ch** [comment]
Unfortunately testing with the latest version produced the same result. Strange case as all the components are correctly set and with the right versions yet it crashed with BSDO "Secure kernel error"

**Comment by gerhart01** [comment]
Attach LiveCloudKd to guest OS and show output

**Comment by JustaT3ch** [comment]
C:\tmp\x64>LiveCloudKd.exe /v 2
      LiveCloudKd for securekernel debugging - 2.5.5.20221109 (special build)
      Microsoft Hyper-V Virtual Machine Live Kernel Debugger
      Copyright (C) 2010-2020, Matthieu Suiche (@msuiche)

      All rights reserved.

      Hyper-V VM memory access operations based on hvlib developed by Arthur Khudyaev (@gerhart_x)
      EXDi debug engine developed by Arthur Khudyaev (@gerhart_x)

   Virtual Machines:
    --> [0] win11 (PartitionId = 0x8, Full VM)

   Please select the ID of the virtual machine you want to play with
   > 0
   You selected the following virtual machine: win11

   Action List:
    --> [0] Live kernel debugger
    --> [1] Linear physical memory dump
    --> [2] Microsoft crash memory dump

   Please select the Action ID
   > 0
hvlib:Guest OS securekernel.exe base address = 0xfffff80686121000
hvlib:Guest OS NT-kernel base address = 0xfffff80680000000
   FunctionTable.ContextPageIndex 100028980, CPU[0]
KiExcaliburData.KiProcessorBlock 0xfffff80680d1f940
FunctionTable.ContextVa 0xffffce81e375c980
FunctionTable.FileSize.QuadPart = 0x102002000
Successfully found module api-ms-win-core-file-l1-1-0.dll
Successfully found function CreateFileW
Successfully found module api-ms-win-core-memory-l1-1-0.dll
Successfully found function CreateFileMappingW
Successfully found module api-ms-win-core-memory-l1-1-0.dll
Successfully found function MapViewOfFile
Successfully found module api-ms-win-core-memory-l1-1-0.dll
Successfully found function UnmapViewOfFile
Successfully found module api-ms-win-core-file-l1-1-0.dll
Successfully found function GetFileSize
Successfully found module api-ms-win-core-memory-l1-1-0.dll
Successfully found function VirtualProtect
Successfully found module api-ms-win-core-handle-l1-1-0.dll
Successfully found function CloseHandle
Successfully found module api-ms-win-core-handle-l1-1-0.dll
Successfully found function DuplicateHandle
Successfully found module api-ms-win-core-file-l1-1-0.dll
Successfully found function SetFilePointer

**Comment by gerhart01** [comment]
Perfect. It means, that LiveCloudKd can found and NT-kernel base and securekernel base addresses in your environment.
It hard to understood, why NT-kernel base is not showing in EXDi plugin.
I will reinstall Windows Server 2019 and setup LiveCloudKd again, because current public version works for me, but it take a time.

**Comment by JustaT3ch** [comment]
I understand, I will try to reinstall the systems and try again to find the difference

Can you specify again what the version of the hos, guest and livekd you are using ?

**Comment by gerhart01** [comment]
Host - Windows server 2019 (with August 2020 updates)
Guest - Windows 11 version 22H2 (September 2023 updates)
WinDBG ex. Preview - 1.2308.2002.0
LiveCloudKd - https://github.com/gerhart01/LiveCloudKd/releases/download/v1.0.22021109/LiveCloudKd.EXDi.debugger.v1.0.22021109.zip

**Comment by JustaT3ch** [comment]
After re-installing the guest I discovered that vt-x support seem to be the cause of the crashes

**Comment by gerhart01** [comment]
Does you disable vt-x inside guest OS? Securekernel had started without it

**Comment by JustaT3ch** [comment]
I disabled vt-x inside the guest OS

**Comment by JustaT3ch** [comment]
I do wonder how features such as HVCI inside the guest OS without hypervisor on

**Comment by gerhart01** [comment]
Yes, that option was written at https://github.com/gerhart01/LiveCloudKd/blob/master/ExdiKdSample/LiveDebugging.md.
"Don't enable nested virtualization support for guest OS. VBS in guest Hyper-V VM works without guest hypervisor."
I think, that host OS hypervisor works with guest OS VBS options.

Any errors after reinstall host OS still present?

**Comment by JustaT3ch** [comment]
Yes, unfortunately on a different PC(Where the issue was first tested) the issue keeps happening even with the vt-x disabled on the host.
the versions are the same. It crashes the system both on ntos and secure kernel once I reload the modules

**Comment by gerhart01** [comment]
Understood, will check it

**Comment by gerhart01** [comment]
Yes, on clean Windows Server 2019 installation debugger can find securekernel
![image](https://github.com/gerhart01/LiveCloudKd/assets/25981258/60958110-3a70-4843-af17-8eb7d83f9285)
Btw, what CPU are you using? I tested it on Intel CPU, but on AMD it can be work too

**Comment by gerhart01** [comment]
Also, check, that symbols for guest OS is loaded correctly, and symbol path is configured for downloading symbols from Microsoft servers

**Comment by JustaT3ch** [comment]
Hi , sorry for the delay in the response
I am using Intel 
The symbols seem to be working correctly and configured for MS server

I will run some more tests and share a dump

**Comment by JustaT3ch** [comment]
Where can I share the kernel dump?

**Comment by JustaT3ch** [comment]
After some testing it seem that when first attaching the debugger, the guest OS restarts(sometimes before loading the symbols and sometimes after) without any crashes. After the restart the debugger seem to work fine even if sometimes the machine freezes and restart is required.
The issue at that point becomes that the base addresses of the ntos and the secure kernel has changes. Is there an option to rescan for the base addresses during the debugging?

**Comment by gerhart01** [comment]
You can share dump on https://mega.io or other service, as you prefer.
If you restart guest OS you need restart debugger - debugger does not process VM id changes. It's not enterprise standard now, unfortunately ;)
The most convenient way now use host OS snapshot after debugger attach to guest OS.

If you can to record video with big it will be perfect, but dump is more preferable

**Comment by JustaT3ch** [comment]
Recording of the described behavior: 
https://mega.nz/file/N78TCAyb#xWIVhW-wQ_zv67Ai-Za8oRhD1_Hkrdjiaw_AK-G2HpI

**Comment by gerhart01** [comment]
Thanks. I tried to translate it to English ...
But symbols is still not configured correctly.

![image](https://github.com/gerhart01/LiveCloudKd/assets/25981258/e4f16bc0-56ef-4e45-806f-49cd1c7fca40)

Please, verify it again

**Comment by JustaT3ch** [comment]
Sorry about the audio , please ignore
You mean both the ntos and the secure kernel symbols must be configured and not only for the secure kernel?

**Comment by JustaT3ch** [comment]
https://mega.nz/file/h2k20ZqB#t-W6j09hPLOYcKJFTbniHRveV8cE_Gd-vQ9oyz-699g

**Comment by gerhart01** [comment]
You still have
![image](https://github.com/gerhart01/LiveCloudKd/assets/25981258/b4463714-cf5b-471a-9d7b-970bdc331c38)
Configure symbols variable on your host VM

**Comment by gerhart01** [comment]
You still have 
![image](https://github.com/gerhart01/LiveCloudKd/assets/25981258/e23df14f-d20e-4595-affa-cfd88f3e4449)
please, configure correct symbol variables on host Hyper-V OS

**Comment by JustaT3ch** [comment]
![image](https://github.com/gerhart01/LiveCloudKd/assets/91199890/9a2efba9-aac9-4b06-b28e-56eaf198048f)


Are you available on twitter ?

**Comment by gerhart01** [comment]
Yes, twitter.com/gerhart_x.
Its good, that you configured symbols. Now primary image base must be found after first debugger launch.

**Comment by JustaT3ch** [comment]
Hi, 
You are not on twitter anymore?

**Comment by gerhart01** [comment]
Halloween )

**Comment by JustaT3ch** [comment]
Gotcha 
Second best after charismas :)

**Comment by gerhart01** [comment]
Find base kernel modules and start debugging is working, but unstable, therefore opened new case for that.
That case is closed.

https://github.com/gerhart01/LiveCloudKd/issues/16

**Comment by gerhart01** [comment]
Find base kernel modules and start debugging is working, but unstable, therefore opened new case for that.
This case is closed.

https://github.com/gerhart01/LiveCloudKd/issues/16
