### ISSUE TITLE
Error: "Interface is not implemented by COM server."

### ISSUE THREAD

**Issue by AdrianoBrugnoni** [gerhart01/LiveCloudKd#15]
![immagine](https://github.com/gerhart01/LiveCloudKd/assets/45570515/44d52155-433b-47fa-adab-f7f39c578826)

<details><summary>Details</summary>
<p>

Microsoft (R) Windows Debugger Version 10.0.22621.2428 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

Interface is not implemented by COM server. ExecuteServerCommand() failed getting the IeXdiControlComponentFunctions pointer: 0x80004002
Kernel Debugger connection established
Found Module Name ntkrnlmp
Found Module Name ntkrnlmp
Could not find the location of KdVersionBlock. Please enable the verbose mode for more details.
Found NT kernel image at fffff80553a07000
Found Module Name ntkrnlmp
Found Module Name ntkrnlmp
Found Module Name ntkrnlmp
Could not find the location of KdVersionBlock. Please enable the verbose mode for more details.
Found Module Name ntkrnlmp
Found Module Name ntkrnlmp
Could not find the location of KdVersionBlock. Please enable the verbose mode for more details.
Found Module Name ntkrnlmp
Found Module Name ntkrnlmp
Could not find the location of KdVersionBlock. Please enable the verbose mode for more details.
Found Module Name ntkrnlmp
Found Module Name ntkrnlmp
Could not find the location of KdVersionBlock. Please enable the verbose mode for more details.
Found Module Name ntkrnlmp
Found Module Name ntkrnlmp
Could not find the location of KdVersionBlock. Please enable the verbose mode for more details.
Could not find NT kernel location based on program counter register.
Could not find the location of KdVersionBlock. Please enable the verbose mode for more details.
Debug API version does not match system version
64-bit machine not using 64-bit API
Debugger data list address is NULL
Connected to eXDI Device 0 x64 target at (Wed Dec  6 01:45:55.555 2023 (UTC + 1:00)), ptr64 TRUE

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*c:\Symbols*http://msdl.microsoft.com/download/symbols
Symbol search path is: srv*c:\Symbols*http://msdl.microsoft.com/download/symbols
Executable search path is: 
Module List address is NULL - debugger not initialized properly.
WARNING: .reload failed, module list may be incomplete
KdDebuggerDataBlock not available!
KdDebuggerData.KernBase < SystemRangeStart
eXDI Device Kernel Version 0 UP Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Machine Name:
Primary image base = 0x00000000`00000000 Loaded module list = 0x00000000`00000000
System Uptime: not available
fffff805`53dd00cd 48c1e220        shl     rdx,20h
0: kd> !pcr
Unable to read the PCR at fffff8055285d000
0: kd> x nt!ZwProtectVirtualMemory
           ^ Couldn't resolve 'x nt'

</p>
</details>

I got this behavior. What's the problem?
I have no problem with Live kernel debugger (menù entry 0). I have problems only with EXDi plugin.

**Host Machine**: Windows 10 Pro (Build 19041)
**Guest Machine**: Windows 11 Enterprise (Build 22621)

**Comment by gerhart01** [comment]
Hello.
Use WinDBG with modern UI with EXDi plugin
<img width="1299" alt="Hyper-V and LiveCloudKd Exdi plugin" src="https://github.com/gerhart01/LiveCloudKd/assets/25981258/7fc76e17-da28-48ea-ac3e-fbc194785f9d">

**Comment by gerhart01** [comment]
If you want to make breakpoint - use Windows Server 2019 with August 2020 updates.
https://github.com/gerhart01/LiveCloudKd/blob/master/ExdiKdSample/LiveDebugging.md

**Comment by gerhart01** [comment]
You can install VMware and run Windows Server 2019 inside - i don't think, that is a problem.

**Comment by gerhart01** [comment]
SLAT is available since 2010? ...
If you have special hardware for research, you can install additional OS, which are booting from VHDX. 15-20 Gb.
I don't recommend to run debugger on standard working desktop\laptop, because it communicate with hypervisor on your host OS.

**Comment by gerhart01** [comment]
Thanks for comments. I will fix it together with issue https://github.com/gerhart01/LiveCloudKd/issues/14
LiveCloudKd debugger worked in my research cases - i read, that USB DCI debugging is working perfectly in that cases, therefore didn't testing LiveCloudKd debugger so deeply.

**Comment by gerhart01** [comment]
Search kernel base and EXDi module launch work.
Unstable debugging operation will be discussed in 
https://github.com/gerhart01/LiveCloudKd/issues/16

This case is closed/
