### ISSUE TITLE
[Q] GVA to GPA

### ISSUE THREAD

**Issue by twisted89** [gerhart01/LiveCloudKd#5]
Maybe I've misunderstood it's exact usage but are their limitations to using SdkMmGetPhysicalAddress/SdkHvmmHvTranslateVA?
It seems to be very temperamental in what it returns, often returning only the last 3 bytes (Page aligned) of the GVA passed in.

I would expect to be able to pass in the Virtual Address of a process within the VM and get back a physical address, or is this not it's intended usage? 

EDIT:
Upon further testing it's clear it only works for kernel space addresses, usermode addresses seem to be broken and return weird values. 

For anyone else with this issue it's easy enough to calculate the GVA -> GPA on a per process basis by walking the EPROCESS DirectoryTableBase.

**Comment by gerhart01** [comment]
Yes, WinHvTranslateVa works only for guest OS kernel mode address space.
