### ISSUE TITLE
Hvlib.dll fails to decode KDBG for Windows 11 Guest

### ISSUE THREAD

**Issue by VinceCodes** [gerhart01/LiveCloudKd#6]
Hello,

I would like to signal that the scan for the KDBG is failing for Windows 11 Guests (Build 22000.556).
I double checked that the structure is not paged out (disabled paging on guest) and that nested virtualization is not enabled. I think that there is perhaps something different regarding the decoding algorithm on windows 11 for the structure or something else that broke the search for `KiWaitAlways`, `KiWaitNever` in hvlib.

Resolution is successful at earlier stages of boot, when the structure is not yet encoded.

**Comment by gerhart01** [comment]
Hello. Thanks for comment - i will see problem.

**Comment by gerhart01** [comment]
See new release - https://github.com/gerhart01/LiveCloudKd/releases/download/v2.5.5.20210814/LiveCloudKd.v2.5.5.20220419-release.zip, it works for Windows 11 x64 April 2022 updates (host and guest)

**Comment by VinceCodes** [comment]
Amazing, thank you for checking this out!
