### ISSUE TITLE
search path of hvlib.dll in leechcore_device_hvmm.dll

### ISSUE THREAD

**Issue by wilhelmw201** [gerhart01/LiveCloudKd#7]
From https://github.com/ufrisk/LeechCore/issues/30
search path of hvlib.dll should also include the directory where leechcore_device_hvmm.dll is located 

currently it looks like leechcore_device_hvmm.dll only looks for hvlib.dll in the current directory , but usually hvlib.dll is next to  leechcore_device_hvmm.dll, which can be anywhere.

**Comment by gerhart01** [comment]
Oh, sorry for delay, email notification messages in github was broken )
Yes, hvlib.dll must be placed in same directory with leechcore_device_hvmm.dll and hvmm.sys for working. Or you have some problem with it if you place all binaries in the Python \Lib\site-packages\leechcorepyc?
