### ISSUE TITLE
LiveCloudKd plugin link in the READ.me outdated/not working, latest plugin from release working fine. 

### ISSUE THREAD

**Issue by ullMarksin** [gerhart01/LiveCloudKd#9]
Just if someone having trouble.

**Comment by gerhart01** [comment]
You are wrong )
https://github.com/gerhart01/LiveCloudKd/releases/download/v2.5.5.20220914/leechcore_hyperv_plugin_14.09.2022.zip is latest plugin and working too.
At least no open issues for it.
